version: 2

before:
  hooks:
    - go mod tidy
    - mkdir -p .buildcache/completions
    - sh -c "go run ./cmd/gomdlint completion bash > .buildcache/completions/gomdlint.bash"
    - sh -c "go run ./cmd/gomdlint completion zsh > .buildcache/completions/gomdlint.zsh"
    - sh -c "go run ./cmd/gomdlint completion fish > .buildcache/completions/gomdlint.fish"

builds:
  - id: gomdlint
    main: ./cmd/gomdlint
    binary: gomdlint
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
      - freebsd
      - openbsd
      - netbsd
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: openbsd
        goarch: arm64
      - goos: netbsd
        goarch: arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - id: default
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md
      - src: .buildcache/completions/*
        dst: completions
        strip_parent: true

checksum:
  name_template: 'checksums.txt'

changelog:
  disable: true

release:
  draft: false
  prerelease: auto
  name_template: "v{{.Version}}"
  make_latest: true
  header: |
    ## What's Changed

    See [CHANGELOG.md](https://github.com/yaklabco/gomdlint/blob/main/CHANGELOG.md) for full details.

brews:
  - name: gomdlint
    repository:
      owner: yaklabco
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    commit_author:
      name: YakLabs
      email: official@yaklab.org
    homepage: "https://github.com/yaklabco/gomdlint"
    description: "Fast Markdown linter with autofix support"
    license: "Apache-2.0"
    install: |
      bin.install "gomdlint"
      bash_completion.install "completions/gomdlint.bash" => "gomdlint"
      zsh_completion.install "completions/gomdlint.zsh" => "_gomdlint"
      fish_completion.install "completions/gomdlint.fish"
    test: |
      system "#{bin}/gomdlint", "version"


