version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: gomdlint
    main: ./cmd/gomdlint
    binary: gomdlint
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - id: default
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md

checksum:
  name_template: 'checksums.txt'

changelog:
  disable: true

release:
  draft: false
  prerelease: auto
  name_template: "v{{.Version}}"
  make_latest: true
  header: |
    ## What's Changed

    See [CHANGELOG.md](https://github.com/jamesainslie/gomdlint/blob/main/CHANGELOG.md) for full details.


