// Code generated by "stringer -type=NodeKind -trimprefix=Node"; DO NOT EDIT.
// This file is manually created to avoid requiring go generate during build.

package mdast

func (i NodeKind) String() string {
	switch i {
	case NodeDocument:
		return "Document"
	case NodeParagraph:
		return "Paragraph"
	case NodeHeading:
		return "Heading"
	case NodeList:
		return "List"
	case NodeListItem:
		return "ListItem"
	case NodeBlockquote:
		return "Blockquote"
	case NodeCodeBlock:
		return "CodeBlock"
	case NodeThematicBreak:
		return "ThematicBreak"
	case NodeHTMLBlock:
		return "HTMLBlock"
	case NodeText:
		return "Text"
	case NodeEmphasis:
		return "Emphasis"
	case NodeStrong:
		return "Strong"
	case NodeCodeSpan:
		return "CodeSpan"
	case NodeLink:
		return "Link"
	case NodeImage:
		return "Image"
	case NodeSoftBreak:
		return "SoftBreak"
	case NodeHardBreak:
		return "HardBreak"
	case NodeHTMLInline:
		return "HTMLInline"
	case NodeRaw:
		return "Raw"
	default:
		return "NodeKind(" + uitoa(uint(i)) + ")"
	}
}
