// Code generated by "stringer -type=TokenKind -trimprefix=Tok"; DO NOT EDIT.
// This file is manually created to avoid requiring go generate during build.

package mdast

func (i TokenKind) String() string {
	switch i {
	case TokText:
		return "Text"
	case TokWhitespace:
		return "Whitespace"
	case TokNewline:
		return "Newline"
	case TokHeadingMarker:
		return "HeadingMarker"
	case TokSetextUnderline:
		return "SetextUnderline"
	case TokListBullet:
		return "ListBullet"
	case TokListNumber:
		return "ListNumber"
	case TokBlockquoteMarker:
		return "BlockquoteMarker"
	case TokCodeFence:
		return "CodeFence"
	case TokCodeFenceInfo:
		return "CodeFenceInfo"
	case TokEmphasisMarker:
		return "EmphasisMarker"
	case TokLinkOpen:
		return "LinkOpen"
	case TokLinkClose:
		return "LinkClose"
	case TokParenOpen:
		return "ParenOpen"
	case TokParenClose:
		return "ParenClose"
	case TokImageMarker:
		return "ImageMarker"
	case TokBacktick:
		return "Backtick"
	case TokEscapedChar:
		return "EscapedChar"
	case TokHTML:
		return "HTML"
	case TokThematicBreak:
		return "ThematicBreak"
	case TokOther:
		return "Other"
	default:
		return "TokenKind(" + uitoa(uint(i)) + ")"
	}
}

func uitoa(val uint) string {
	if val == 0 {
		return "0"
	}
	var buf [20]byte
	i := len(buf) - 1
	for val > 0 {
		buf[i] = byte(val%10) + '0'
		val /= 10
		i--
	}
	return string(buf[i+1:])
}
